name: Support Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  stats:
    name: Collect stats
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      GUILD_ID: "830184174198718474"
      SUPPORT_CHANNEL: "1019713903481081876"
      SUPPORT_SQUAD_CHANNEL: "916064458814681218"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup node@22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Collect
        run: pnpm collect:stats
